### ISSUE TITLE
Key Concepts >> Membership Service Provider (MSP)

### ISSUE THREAD

**Issue by nekia** [hyperledger/fabric-docs-i18n#116]
https://hyperledger-fabric.readthedocs.io/ja/release-2.2/membership/membership.html
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/membership/membership.md

**Comment by siburu** [comment]
I will work on this.

**Comment by satota2** [comment]
@siburu こちらの翻訳の状況はいかがでしょうか。
もし、翻訳が難しいようでしたら一旦Assignを解除することも可能です。なお、2週間経過しても返答いただけない場合、FabricのAging Policyに従ってAssignを自動的に解除させていただき、ほかの方が引き継ぐこととなりますのでご承知おきください。
