### ISSUE TITLE
[es] whatis.md issues

### ISSUE THREAD

**Issue by rodrigomelo9** [hyperledger/fabric-docs-i18n#180]
Hi @claudiocebpaz I found 3 issues in [this](https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/es/source/whatis.md) translation:

- [x] Introduccion -> Introducción 
- [x] Missing translation for the paragraph starting with: *While many early blockchain platforms are currently being ...*
- [x] The paragraph starting with "Additionally, in such a permissioned context, the risk of a participant intentionally introducing malicious code through a smart contract is diminished..." can be deleted, because is already translated.

Regards

**Comment by rodrigomelo9** [comment]
Also, Ordering Service was translated as *Servicio de pedidos* instead of *Servicio de ordenamiento*. See #184 for more info.

**Comment by claudiocebpaz** [comment]
Thanks for working on this.
