### ISSUE TITLE
[es] Inconsistency in how Ordering Service is translated

### ISSUE THREAD

**Issue by rodrigomelo9** [hyperledger/fabric-docs-i18n#184]
Hi @claudiocebpaz. I think that there are inconsistencies in how Ordering Service is translated in the [glossary](https://hyperledger-fabric.readthedocs.io/es/latest/glossary.html#servicio-de-ordenamiento). It begins as *Servicio de Ordenamiento* (the title) and next changes to *servicio de pedidos*. I think better to choose only one name to avoid misunderstands. Moreover, is represented as O in the graphics, so is better to use *Servicio de Ordenamiento*. Take into account that both alternatives are used throughout the entire document.

**Comment by claudiocebpaz** [comment]
Please work on this, and submit a PR.

I agree with your comments.
