### ISSUE TITLE
Architecture Reference » CouchDB as the State Database

### ISSUE THREAD

**Issue by Skurimura** [hyperledger/fabric-docs-i18n#241]
https://hyperledger-fabric.readthedocs.io/en/release-2.2/couchdb_as_state_database.html
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/couchdb_as_state_database.rst

**Comment by Skurimura** [comment]
I will do this

**Comment by satota2** [comment]
@Skurimura こちらの翻訳の状況はいかがでしょうか。
もし、翻訳が難しいようでしたら一旦Assignを解除することも可能です。なお、2週間経過しても返答いただけない場合、FabricのAging Policyに従ってAssignを自動的に解除させていただき、ほかの方が引き継ぐこととなりますのでご承知おきください。
