### ISSUE TITLE
the step "git checkout release-2.2" fail

### ISSUE THREAD

**Issue by jeydi243** [hyperledger/fabric-docs-i18n#26]
Hi everyone! i try the command `git checkout release-2.2` and that this the response:
`error: pathspec 'release-2.2' did not match any file(s) known to git` .
Im trying to respect all step for docs translation describe in [Create a new translation](https://hyperledger-fabric.readthedocs.io/en/release-2.2/international_languages.html) .
Thank you for your help.

**Comment by btl5037** [comment]
You probably cloned fabric before we cut the release-2.2 branch. Do a `git fetch` and then `git checkout release-2.2`

**Comment by jeydi243** [comment]
okay thank you!
