### ISSUE TITLE
【zh_CN】Docs » 操作指南 » 配置并使用 Raft 排序服务 待翻译

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#307]
docs\locale\zh_CN\source\raft_configuration.md
部分段落未翻译

**Comment by sc1000y** [comment]
issue me and I'll pull tonight.

**Comment by sc1000y** [comment]
alread merged and need to be close @stone-ch

**Comment by stone-ch** [comment]
Finished
