### ISSUE TITLE
【Release-2.2】Getting Started » Using the Fabric test network 待翻译

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#35]
文档路径：fabric-docs-i18n/docs/locale/zh_CN/source/test_network.rst

**Comment by ke-chain** [comment]
can i have this issue?

**Comment by ke-chain** [comment]
第一次翻译，有个问题：
 test_network.md已经翻译好了。
test_network.rst还需要做什么？

**Comment by ke-chain** [comment]
@stone-ch  There is already exist test_network.md.is it necessary to translate test_network.rst?

**Comment by stone-ch** [comment]
> @stone-ch There is already exist test_network.md.is it necessary to translate test_network.rst?

你可以选择其他内容翻译。 #38 这个怎么样？
