### ISSUE TITLE
【Release-2.2】Tutorials » Chaincode for Developers 待翻译

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#36]
文档路径：fabric-docs-i18n/docs/locale/zh_CN/source/chaincode4ade.rst

**Comment by bolenzhang** [comment]
Assign me, please, I would like to translate this document into Chinese.

**Comment by stone-ch** [comment]
@bolenzhang  这篇你翻译完没？我今天看这章就顺手翻译了

**Comment by bolenzhang** [comment]
@stone-ch 好吧 本来打算这周找一天翻译的。。。

**Comment by stone-ch** [comment]
好，那我就上传了，你翻译其他的吧

**Comment by stone-ch** [comment]
finished
