### ISSUE TITLE
【zh_CN】Docs » 教程» 使用测试网络 翻译错误修改

### ISSUE THREAD

**Issue by LohkoCoder** [hyperledger/fabric-docs-i18n#369]
原文：docs/locale/zh_CN/source/test_network.md
链接：https://hyperledger-fabric.readthedocs.io/zh_CN/release-2.2/test_network.html

文档中的部署合约部分的操作并不正确（需要指定合约名、路径等信息），需要参考https://hyperledger-fabric.readthedocs.io/en/release-2.2/test_network.html英文原文进行修改

**Comment by stone-ch** [comment]
这个你是不是已经完成了？@ZJJ-XYH

**Comment by ZJJ1991** [comment]
> 这个你是不是已经完成了？@ZJJ-XYH

是的，已经完成了

**Comment by stone-ch** [comment]
Done #382
