### ISSUE TITLE
【Release-2.2】Tutorials » Adding an Org to a Channel 待翻译  

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#37]
文档路径：fabric-docs-i18n/docs/locale/zh_CN/source/channel_update_tutorial.rst

**Comment by bolenzhang** [comment]
Assign me, please, I would like to translate this document into Chinese.

**Comment by stone-ch** [comment]
> Assign me, please, I would like to translate this document into Chinese.

It is your task now.

**Comment by bolenzhang** [comment]
@stone-ch stone-ch  我现在翻译完这篇了，请问可以以markdown格式提交吗？ 还是必须得rst格式的

**Comment by stone-ch** [comment]
按照原文的格式提交
