### ISSUE TITLE
【Release-2.2】Tutorials » Using CouchDB 待翻译

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#38]
文档路径：fabric-docs-i18n/docs/locale/zh_CN/source/couchdb_tutorial.rst

**Comment by stone-ch** [comment]
@ke-chain can you translate this one?

**Comment by ke-chain** [comment]
@stone-ch  ok,give it to me . and sorry for getting back to you late~

**Comment by stone-ch** [comment]
Finished
