### ISSUE TITLE
【Release-2.2】Operations Guides » Chaincode as an external service 待翻译

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#39]
文档路径：fabric-docs-i18n\docs\locale\zh_CN\source\cc_service.md

**Comment by stone-ch** [comment]
Assign me, please, I would like to translate this document into Chinese.

**Comment by stone-ch** [comment]
Anyone else want to translate this article?

**Comment by ZJJ-XYH** [comment]
I'd like to do this.

**Comment by stone-ch** [comment]
Finished
