### ISSUE TITLE
translation of glossary page

### ISSUE THREAD

**Issue by satomicchy** [hyperledger/fabric-docs-i18n#43]
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/glossary.rst

**Comment by Naoya-Horiguchi** [comment]
Let me work on this 😃 

Please note that a single issue can have multiple assignees, so if you are interested in this file, feel free to add yourself to assignee list.

**Comment by Naoya-Horiguchi** [comment]
I found a suspicious line in original `glossary.rst`, so I made a [PR](https://github.com/hyperledger/fabric/pull/1666) to fix it. I would translate assuming that this suggestion is accepted.

**Comment by Naoya-Horiguchi** [comment]
I'm publishing [a WIP branch](https://github.com/Naoya-Horiguchi/fabric-docs-i18n/blob/glossary/docs/locale/ja_JP/source/glossary.rst). `glossary.rst` is relatively large, so I feel it's better to keep showing the latest status to get comment timely. Any comment/help on it is welcomed.

**Comment by Naoya-Horiguchi** [comment]
Close this issue because it's done.
