### ISSUE TITLE
translation of CONTRIBUTING page

### ISSUE THREAD

**Issue by satomicchy** [hyperledger/fabric-docs-i18n#47]
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/CONTRIBUTING.rst

**Comment by Skurimura** [comment]
Hi, can I start working for this one?

**Comment by satomicchy** [comment]
Yes, thank you! It does not need an authorization when you start translating, please just say "I will do"!

**Comment by Skurimura** [comment]
Translation is in progress.
