### ISSUE TITLE
Synchronize to Tutorials >> Chaincode for Developers

### ISSUE THREAD

**Issue by satomicchy** [hyperledger/fabric-docs-i18n#532]
From:
https://github.com/hyperledger/fabric/blob/release-2.2/docs/source/chaincode4ade.rst
in the commit `9a6b35104e88dc2df08db7c7b0ba3d0f61127a85`
To:
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/chaincode4ade.rst

**Comment by satomicchy** [comment]
@shimos @satota2 本家ドキュメントへの同期で、変更が大きいファイルのissueを立ててみました。こんな感じでどうでしょう？

**Comment by shimos** [comment]
@satomicchy ありがとうございます。こんな感じでいいと思います。
なお、本家側の差分は、https://github.com/hyperledger/fabric/compare/v2.2.0..release-2.2#files_bucket でdocs/source/chaincode4ade.rstのdiffを開くとみられるようです。(URLで1ファイルだけ指定することはできないようです...)
