### ISSUE TITLE
[ja_JP] Update "Tutorials >> Deploying a smart contract to a channel"

### ISSUE THREAD

**Issue by shimos** [hyperledger/fabric-docs-i18n#533]
From:
https://github.com/hyperledger/fabric/blob/9a6b35104e88dc2df08db7c7b0ba3d0f61127a85/docs/source/deploy_chaincode.md

To:
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/deploy_chaincode.md

**Comment by satomicchy** [comment]
@shimos 元のファイルのfabricリポジトリでのコミット番号がわからなくなってしまったのですが、どうやって調べたらいいでしょうか？

**Comment by shimos** [comment]
@satomicchy 自分もja_JPを作ったのがどのcommitだったのかわからなかったので、このissueを立てたときにはURLで参照している通り、 9a6b35104e88dc2df08db7c7b0ba3d0f61127a85 を時間軸的に近そうなものとして、基準としました（なのでやっぱり不正確な可能性があります）

**Comment by satomicchy** [comment]
@shimos 上記コミットを見ると日付がThu Jul 22 07:30:43 2021なので、このファイルに関してはもう一年前ほどになると思います。現状のfabricとdiffしても1行しか差分がありませんでしたし、initial commitがJul 13, 2020で、私が作ったものでしたので。。。すみません、私がメモしてなかったのが原因ですね。
pull reqする際にはどれを参考にしたかをコメントでつけるようにします。
