### ISSUE TITLE
【Release-2.2】Tutorials » Creating a channel » Channel policies 待翻译

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#55]
文档路径：docs\locale\zh_CN\source\create_channel\channel_policies.md

**Comment by pengisgood** [comment]
@stone-ch assign to me, please.

**Comment by pengisgood** [comment]
Please review the PR.

**Comment by pengisgood** [comment]
@stone-ch help to close this issue, please.
