### ISSUE TITLE
[ja_JP] Tutorials >> Secured asset transfer in Fabric

### ISSUE THREAD

**Issue by satota2** [hyperledger/fabric-docs-i18n#564]
https://hyperledger-fabric.readthedocs.io/en/release-2.2/secured_asset_transfer/secured_private_asset_transfer_tutorial.html
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/secured_asset_transfer/secured_private_asset_transfer_tutorial.md

**Comment by satomicchy** [comment]
@shimos 文中で英語のtypoかもしれないと思う箇所がありました。Figure 3の説明文に"The asset ownership record on the ledger is updated to reflect that the asset is owned by Org1."とあります。ここはOrg2にassetが移ったあとなので、"...owned by Org2."のように思うのですが、いかがでしょうか？

**Comment by shimos** [comment]
@satomicchy はい、自分もこれは"owned by Org2"のtypoだと思います。

**Comment by satomicchy** [comment]
@shimos ありがとうございます。では、日本語のほうはOrg2にしておきます。本家のほうへは折をみてpull reqしてみたいと思います。
