### ISSUE TITLE
【Release-2.2】Tutorials » Creating a channel » Using configtx.yaml to build a channel configuration 待翻译

### ISSUE THREAD

**Issue by stone-ch** [hyperledger/fabric-docs-i18n#57]
文档路径：docs\locale\zh_CN\source\create_channel\create_channel_config.md

**Comment by pengisgood** [comment]
@stone-ch  assign to me, please.

**Comment by pengisgood** [comment]
covered in PR: https://github.com/hyperledger/fabric-docs-i18n/pull/92

Please have a review.

**Comment by pengisgood** [comment]
@stone-ch since the pr has been merged, could you please close this issue?
