### ISSUE TITLE
[ja_JP] Operations Guides » Pluggable transaction endorsement and validation

### ISSUE THREAD

**Issue by satota2** [hyperledger/fabric-docs-i18n#584]
https://hyperledger-fabric.readthedocs.io/en/release-2.2/pluggable_endorsement_and_validation.html
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/pluggable_endorsement_and_validation.rst

**Comment by nekia** [comment]
長らく抱え込んでしまって申し訳ありませんでした。着手できておりませんので一度手放します。 😓
