### ISSUE TITLE
[ja_JP] Deploying a production network » Deploy the ordering service

### ISSUE THREAD

**Issue by satota2** [hyperledger/fabric-docs-i18n#602]
https://hyperledger-fabric.readthedocs.io/en/release-2.2/deployorderer/ordererdeploy.html
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/deployorderer/ordererdeploy.md

**Comment by satomicchy** [comment]
@satota2 本文中、L70,L83に "If you are using a containerized solution for running your network..."という全く同じ段落が出てきます。どちらか消し忘れのような気もするのですが、どうでしょうか？

**Comment by satota2** [comment]
@satomicchy
段落構造的にはTLS certsのほう(L.83)は無くてよい気もします。ただTLS certsのほうもvolumeマウントが必要と念押しするために意図的に記載している可能性もなくはなさそうです。
本家のほうに修正パッチを投げてみてメンテナの反応を伺ってみてもよいかもしれませんね。

**Comment by satomicchy** [comment]
@satota2 コメントありがとうございます！一旦、このまま日本語にしておきます。本家のほうは折を見てパッチ投げてみます。
