### ISSUE TITLE
[ja_JP] Operations Guides » Metrics Reference

### ISSUE THREAD

**Issue by satota2** [hyperledger/fabric-docs-i18n#603]
https://hyperledger-fabric.readthedocs.io/en/release-2.2/metrics_reference.html
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/metrics_reference.rst

**Comment by satomicchy** [comment]
@satota2 このページの翻訳は、表内のDescriptionの部分と、表外の説明文だけでいいでしょうか？

**Comment by satota2** [comment]
@satomicchy
> 表内のDescriptionの部分と、表外の説明文だけでいいでしょうか？

ご担当ありがとうございます。そうですね、それでよいと思います。
