### ISSUE TITLE
[ja_JP] Commands Reference » peer

### ISSUE THREAD

**Issue by satota2** [hyperledger/fabric-docs-i18n#604]
https://hyperledger-fabric.readthedocs.io/en/release-2.2/commands/peercommand.html
https://github.com/hyperledger/fabric-docs-i18n/blob/release-2.2/docs/locale/ja_JP/source/commands/peercommand.md

**Comment by satota2** [comment]
@e-maekawa お疲れ様です。
こちらの作業状況いかがでしょうか？
実は私のほうで担当間違えてこのページを途中まで訳してしまいまして、、もしまだ翻訳に着手されていないようで、かつ、もしよろしければ、こちらのページを私のほうで引き継がせて頂くのも手と思いまして状況お伺いした次第です。
よろしくお願いします。

**Comment by e-maekawa** [comment]
Tatsuya Sato様

はい、引き継いでいただいて大丈夫です。
翻訳をお願いします。
最近翻訳にあまり参加できて申し訳ないです・・・

よろしくお願いします。

前川


On Thu, 26 Jan 2023 18:52:43 -0800
Tatsuya Sato ***@***.***> wrote:

> @e-maekawa お疲れ様です。
> こちらの作業状況いかがでしょうか？
> 実は私のほうで担当間違えてこのページを途中まで訳してしまいまして、、もしまだ翻訳に着手されていないようで、かつ、もしよろしければ、こちらのページを私のほうで引き継がせて頂くのも手と思いまして状況お伺いした次第です。
> よろしくお願いします。
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/hyperledger/fabric-docs-i18n/issues/604#issuecomment-1405953687
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
emi maekawa ***@***.***>

**Comment by satota2** [comment]
@e-maekawa
返信ありがとうございます。

> はい、引き継いでいただいて大丈夫です。

承知いたしました。ではこちらのページに関しては引き継がせて頂きます。

> 最近翻訳にあまり参加できて申し訳ないです・・・

いえいえ、オープンソース活動なのでお気になさらず。
私もここしばらく翻訳活動できていなかったのですが、最近またパッチ投稿再開した感じです。
ぜひお時間あるときにご参加いただけるとうれしいです。
