### ISSUE TITLE
【Release-2.0】translation improvement（gossip part）

### ISSUE THREAD

**Issue by SennriSyunnga** [hyperledger/fabric-docs-i18n#76]
经群里的用户neswater介绍，说翻译的建议或者纠错可以发在这里，
本来打算回复在2.2的译文底下，但好像没有，只好另开一个issue，
苦于置顶内容中没有提及这类反馈该以何种格式发布issue本来打算作罢
群友说不用太介意这个，因此先冒昧地发这里，管理员阅读后可以删除。

出处：https://hyperledger-fabric.readthedocs.io/zh_CN/latest/gossip.html
Anchor Node 部分：
原文：
> From that point forward, organizations A and B would start exchanging membership information directly without any assistance from peer0.orgC.
现译文：
> 就像之前所说的，组织 A 和 B 可以不通过 peer0.orgC 而直接交换成员信息。

个人认为翻译应该是：
在这之后，组织A和组织B可以开始直接交换成员信息而无需借助peer0.orgC了。

**Comment by davidkhala** [comment]
感谢贡献，我就是群主neswater

**Comment by stone-ch** [comment]
感谢贡献，因为迁移到 2.2 的翻译文档是从 2.0 迁移过来的，有些章节需要整理，整理完的才会开issue让大家认领。我稍后先把这篇文档整理出来，纠正翻译不当的内容。

**Comment by stone-ch** [comment]
已经在 2.2 中更新翻译内容
