### ISSUE TITLE
[ja_JP] Architecture Reference / Fabric Gateway

### ISSUE THREAD

**Issue by shimos** [hyperledger/fabric-docs-i18n#907]
Original HTML: https://hyperledger-fabric.readthedocs.io/en/release-2.5/gateway.html
Original Source: https://github.com/hyperledger/fabric/blob/e1e8e2e52aa4fc543360d245fe6554a0eaf81183/docs/source/gateway.md

**Comment by pugsatoshi** [comment]
本件、どなたもAssignされていないようですので、私の方で翻訳いたします。よろしくお願いいたします。
