### ISSUE TITLE
[ja_JP] Architecture Reference / Performance considerations

### ISSUE THREAD

**Issue by shimos** [hyperledger/fabric-docs-i18n#912]
Original HTML: https://hyperledger-fabric.readthedocs.io/en/release-2.5/performance.html
Original Source: https://github.com/hyperledger/fabric/blob/e1e8e2e52aa4fc543360d245fe6554a0eaf81183/docs/source/performance.md

**Comment by takayuki-nagai** [comment]
本件、まだどなたもAssignされていないようですので、当方にて翻訳を担当させて頂ければと存じます。よろしくお願いいたします。
