### ISSUE TITLE
【zh_CN】Docs » 关键概念 » 区块链网络 图文不一致

### ISSUE THREAD

**Issue by myot233** [hyperledger/fabric-docs-i18n#922]
观察英文release-2.5同页面
[en](https://hyperledger-fabric.readthedocs.io/en/release-2.5/network/network.html)
中文release-2.5同页面  
[zh_cn](https://hyperledger-fabric.readthedocs.io/zh-cn/latest/network/network.html)
发现图文不一致

**Comment by Chengxuan** [comment]
Raised https://github.com/hyperledger/fabric-docs-i18n/pull/923 for this
