### ISSUE TITLE
Add Org offboarding to Operation Guides

### ISSUE THREAD

**Issue by takakir** [hyperledger/fabric-docs-i18n#925]
Wanted to know if the community would like our team to add org offboarding procedures to Operations Guides.

Currently testing out org offboarding procedures w/  @kaiknight and wondering if it would also benefit the community if we share the results as one of the operation guide doc.

Happy to draft doc and submit pull request if appropriate & required.

**Comment by satota2** [comment]
Hello @takakir 

Thank you for your proposal. Sorry but this repository manages translations of Fabric's original documentation, and new documentation additions are handled within the Fabric main repository.
So, could you please re-submit the same issue here?
https://github.com/hyperledger/fabric/issues/new?assignees=&labels=enhancement&projects=&template=feature.yaml

I can also re-submit the issue on your behalf if that would be easier for you.

Furthermore, I beleave that the document you're proposing would be highly beneficial for the community.
We would be delighted if you could draft the document and submit a pull request.

**Comment by takakir** [comment]
Thanks. Will resubmit.
